= projet M1 MIAGE - semestre 1
Frédéric Moal, Yohan Boichut
version 2019-2020



== Contexte
Le sujet est relatif à la gestion des projets Dill pour lesquels une partie de la promotion de cette année en fait l'expérience. Le but du jeu est de gérer ces projets du dépôt d'une proposition par une entreprise au vote final du meilleur projet par les différents acteurs.

* Acteurs : étudiant, entreprise, enseignant, admin


== Fonctionnalités

Les fonctionnalités sont divisées en 2 lots. Le trinôme issu de la formation initiale sera responsable du lot 1. Le trinôme issu
de la formation apprentissage/alternance  sera responsable du lot 2. Les fonctionnalités transverses sont issues des deux lots.
Les étudiants ajoutés rejoignent le trinôme des apprentis/alternants. Une bonne organisation et une bonne communication seront
indispensables pour mener le projet à son terme. Les lots sont loin d'être indépendants. Il faudra donc bien communiquer pour qu'au final,
nous ayons une belle démonstration lors des soutenances finales.




=== Lot 1 -- trinôme formation initiale

* Administrateur
** import de listes d'étudiants depuis csv
** paramétrages & algos
*** définir les contraintes sur les choix des projets par les étudiants
eg nombre de choix min/max, au moins un projet d'Orléans pour les étudiants d'Orléans...
*** définition des dates limites (choix, livrables,...)
*** algorithmeS de répartition [en global ou en stream]
** validations et corrections
*** valider les propositions de projets [=> notifications aux entreprises]
*** validation, modification et publication des résultats (partiels) des attributions des projets
*** compléter les répartitions en manuel

=== Lot 2 -- trinôme alternants/apprentis

* Entreprise
** enregistrement de l'entreprise
** dépôt de propositions de sujets
** visualisation de l'état des propositions (proposition validée, affectée, composition des groupes)
** enregistrement d'un tuteur par projet pour l'entreprise
(peut être différent de celui qui a déposé le sujet)
** vérification des dépôts des livrables des projets

* Etudiants
** inscription aux projets avec choix des projets par ordre de préférence
** modifications des choix jusqu'à la date limite
** suivi d'avancement et notifications d'attribution à un projet
** visualisation des infos complètes du projet attribué : membres, tuteurs (ens entreprise)
** dépôt de livrables (deadlines avec notifs pour dépôts de documents)

* Enseignant tuteur
** authentification des enseignants par ldap existant
** choix des projets comme tuteurs enseignants
** vérification des dépôts des livrables
** relance des étudiants en retard sur les livrables

=== Fonctionnalités transverses

* gestion des mots de passe perdus
* authentification et gestion des différents rôles
* monitoring des activités des utilisateurs (login, ...)
* Votes : nous devons proposer un système de vote "pour le meilleur projet". Chaque acteur pourra classer trois projets.
Les places rapportent un certain nombre de points (qui vous seront précisés ultérieurement). Un acteur ne peut pas voter
pour le(s) projet(s) dans le(s)quel(s) il est impliqué. La phase de vote est ouverte par un administrateur. Un acteur peut
modifier son vote mais ne peut pas voter deux fois. Il peut modifier son vote tant que l'élection est ouverte.
Une fois l'élection terminée, les résultats sont calculés puis publiés par l'administrateur.


== Organisation

* constitution initale de trinômes à faire sur
https://pdicost.univ-orleans.fr/wiki/display/PM1S1/Inscriptions+aux+projets+du+semestre+1
* random 2 trinômes aléatoires pour constituer un groupe

NOTE: projet = 15 points / lot + 1/3 du lot complémentaire
      soutenance [démo] = 10 points

* Les soutenances auront lieu le lundi 20 janvier. Il s'agira d'une démonstration du produit fini, d'un bilan sur les fonctionnalités
et d'un retour sur l'expérience : ce qui a marché, ce qui n'a pas marché, ce que vous auriez dû faire si c'était à refaire.





== Contraintes structurelles

Vous disposez d'un repo Git que vous *DEVREZ* utiliser pour l'ensemble de votre projet :

. code source
. fichiers de configuration
. jeux de données de test/démo pour la validation des lots
. documentation complète (architecture, code, README... )

Votre projet devra être organisé sous la forme d'un projet principal (pom parent)
et de modules pour chaque partie (e.g. modele, appliTexte, appliVueJS...),
Le projet *parent* devra être identifiable par maven (groupid:artifactId) de la façon suivante :
fr.miage.orleans.projetm1s1:groupe?
où ? est la lettre de votre groupe

Le déploiement de l'ensemble de vos applications devra être défini par un fichier docker compose ;
la commande `docker-compose up -d` lancera l'ensemble des composants de votre solution.


== Technos

Vous devrez utiliser les technos suivantes :

* MongoDB (obligatoire)
* MySQL
* kafka
* front Web
* JS : VueJS ou un autre framework après accord des responsables


