version: '3'
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:5.3.1
        hostname: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181

    kafka:
        image: confluentinc/cp-kafka:5.3.1
        hostname: kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    mariadb:
        image: mariadb
        container_name: mariadb
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE:  projet
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            TERM: dumb
        volumes:
            - ./mariadb/db:/var/lib/mysql
    php_myadmin:
            image: phpmyadmin/phpmyadmin
            restart: always
            ports:
                - 8082:80
            depends_on:
                - mariadb
            environment:
                PMA_HOST: mariadb
                MYSQL_ROOT_PASSWORD: root

    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        restart: always
        ports:
            - 27017:27017

    tomcat:
      build: ./projet-dill
      ports:
          - 8888:8080

